npm install --save-dev webpack@3.6.0
npm install --save-dev lodash
npm install --save-dev file-loader
npm install --save-dev csv-loader
npm install --save-dev xml-loader
npm install --save-dev css-loader
npm install --save-dev style-loader
npm install --save-dev html-webpack-plugin
npm install --save-dev clear-webpack-plugin
